//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCitas.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Citas
    {
        public System.Guid Id { get; set; }
        public int Seq { get; set; }
        public System.Guid IdPaciente { get; set; }
        public System.Guid IdSalon { get; set; }

        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }

        [Display(Name = "Hora")]
        [DataType(DataType.Time)]
        // [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyForma
        //
        // tInEditMode = true)]
        public System.TimeSpan Hora { get; set; }
        public string Motivo { get; set; }
        public System.Guid IdEstadoCita { get; set; }
        [Display(Name = "FechaCreado")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaCreado { get; set; }
    
        public virtual EstadoCitas EstadoCitas { get; set; }
        public virtual Salones Salones { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
