//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public System.Guid Id { get; set; }
        public int Seq { get; set; }
        public System.Guid IdPaciente { get; set; }
        public System.Guid IdSalon { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.Guid> IdEstadoCita { get; set; }
        public System.DateTime FechaCreado { get; set; }
    
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Salone Salone { get; set; }
    }
}
